# Generated by Django 3.2.3 on 2021-06-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='mainCycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='backend.maincycle'),
        ),
    ]
